const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function app(){
 const nodes=new Map(); const get=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',style:{},dataset:{},disabled:true,open:true,classList:{toggle(){},add(){}},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(s)};
 const utterances=[];const timers=[];
 class Recognition{start(){this.onstart?.()}stop(){this.onend?.()}abort(){}}
 const context=vm.createContext({console,URL,Blob,window:{SpeechRecognition:Recognition,speechSynthesis:{cancel(){},getVoices(){return [{lang:'fr-FR'},{lang:'de-DE'}]},speak(u){utterances.push(u)}}},document:{querySelector:get,querySelectorAll:()=>[],addEventListener(){},documentElement:{classList:{toggle(){}}}},navigator:{},localStorage:{getItem(){return null},setItem(){}},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){},SpeechSynthesisUtterance:class{constructor(t){this.text=t}}});
 context.speechSynthesis=context.window.speechSynthesis;
 for(const name of ['lessons','hints','speech','app'])vm.runInContext(fs.readFileSync('dist/'+name+'.js','utf8'),context);
 return {run:s=>vm.runInContext(s,context),get,utterances,timers};
}
test('every course phrase has specific usage and sound hints',()=>{const a=app();assert.equal(a.run("Object.values(COURSE).every(c=>c.lessons.every(d=>d.phrases.every(p=>p.length===4&&p[2]&&p[3])))"),true);a.run("openLesson('fr',1)");let first=a.get('#lesson-body').innerHTML;a.run('phraseIndex=1;lessonRender()');let second=a.get('#lesson-body').innerHTML;assert.match(first,/Introduce yourself with/);assert.match(second,/Ask a friend or another child/);assert.doesNotMatch(second,/Enchanté and enchantée/);});
test('speech checks tolerate punctuation, accents and numeric transcription but reject missing/wrong words',()=>{const a=app();for(const [x,y,l]of [['Ça va ?','ca va','fr'],['Ich heiße Alex.','ich heisse Alex','de'],['trois','3','fr'],['fünf','5','de']])assert.equal(a.run(`matchesSpeech(${JSON.stringify(x)},${JSON.stringify(y)},'${l}')`),true);assert.equal(a.run("matchesSpeech('Comment tu t’appelles ?','Comment vous appelez vous','fr')"),false);assert.equal(a.run("matchesSpeech('Bonjour','Bonsoir','fr')"),false);assert.equal(a.run("matchesSpeech('Bonjour','','fr')"),false);});
test('wrong speech and service errors cannot complete a lesson; all phrases must pass',()=>{const a=app();a.run("openLesson('fr',0);step=3;lessonRender();finish()");assert.equal(a.run('state.done.fr.length'),0);a.run("checkSpeech();speechCheck.onresult({resultIndex:0,results:[[{transcript:'Bonsoir'}]]});speechCheck.onend()");assert.equal(a.run('speechPassed.size'),0);a.run("checkSpeech();speechCheck.onerror({error:'network'});speechCheck.onend()");assert.match(a.get('#speech-feedback').textContent,/could not connect/);assert.equal(a.run('speechPassed.size'),0);for(let i=0;i<4;i++)a.run(`speakingIndex=${i};lessonRender();checkSpeech();speechCheck.onresult({resultIndex:0,results:[[{transcript:active.d.phrases[${i}][0]}]]});speechCheck.onend()`);a.run('finish()');assert.equal(a.run('state.done.fr.length'),1);});
test('cancelled recognition result cannot pass another lesson',()=>{const a=app();a.run("openLesson('fr',0);step=3;lessonRender();checkSpeech();var oldResult=speechCheck.onresult;openLesson('de',0);oldResult({resultIndex:0,results:[[{transcript:'Bonjour'}]]})");assert.equal(a.run('speechPassed.size'),0);});
test('slow playback uses lower rate and word pauses; cancelling prevents queued words',()=>{const a=app();a.run("say('Bonjour Alex','fr',false)");assert.equal(a.utterances[0].rate,1);a.run("say('Bonjour Alex','fr',true)");assert.equal(a.utterances[1].rate,.45);assert.equal(a.utterances[1].text,'Bonjour');a.utterances[1].onend();assert.equal(a.utterances.length,2);a.timers.at(-1)();assert.equal(a.utterances[2].text,'Alex');a.run("say('Guten Tag','de',true)");a.utterances[3].onend();a.run('cancelPlayback()');a.timers.at(-1)();assert.equal(a.utterances.length,4);});
